name: Build and Deploy to Netlify

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Runner & repo info
        shell: bash
        run: |
          set -x
          uname -a
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          command -v node || true
          command -v npm || true

      # Bootstrap Node to create a lockfile if missing (avoids cache error)
      - name: Use Node.js (bootstrap)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ensure lockfile (no local build needed)
        shell: bash
        run: |
          set -x
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only 2>&1 | tee npm-lock.log
          fi

      # Re-run with npm cache now that lockfile exists
      - name: Use Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Versions
        shell: bash
        run: |
          set -x
          node -v
          npm -v

      - name: Install dependencies (verbose)
        shell: bash
        env:
          NPM_CONFIG_LOGLEVEL: verbose
        run: |
          set -x
          npm ci --foreground-scripts --timing 2>&1 | tee npm-install.log

      - name: Show dependency tree (top level)
        shell: bash
        run: |
          set -x
          npm ls --depth=0 || true

      - name: Build (Vite with debug + Node traces)
        shell: bash
        env:
          DEBUG: vite:*
          NODE_OPTIONS: --trace-deprecation --trace-warnings
        run: |
          set -x
          npm run build 2>&1 | tee build.log

      - name: Verify dist output
        shell: bash
        run: |
          set -x
          echo "dist contents:"
          ls -la dist
          test -f dist/index.html
          test -f dist/about-pallyflo/index.html
          test -f dist/contact.html

      - name: Install Netlify CLI
        shell: bash
        run: |
          set -x
          npm install -g netlify-cli 2>&1 | tee netlify-install.log

      - name: Deploy to Netlify (production, debug logs)
        shell: bash
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_LOG_LEVEL: debug
        run: |
          set -x
          netlify deploy --dir=dist --prod --message "CI deploy $GITHUB_SHA" 2>&1 | tee deploy.log

      - name: Upload logs and dist snapshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs-and-dist
          path: |
            npm-lock.log
            npm-install.log
            build.log
            netlify-install.log
            deploy.log
            ~/.npm/_logs/**
            dist/**
          retention-days: 7
